# Generated by Django 5.2.8 on 2025-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_orders_orde_created_f0ce29_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_online',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='partial_payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('full', 'Pay Full Amount Online'), ('partial', 'Pay 50% Now, 50% on Delivery')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
